language: minimal
dist: xenial
addons:
  apt:
    packages:
      - npm

before_install:
  - "sudo npm install --global spellchecker-cli"

install:
  - "/usr/local/bin/spellchecker md/*.md"
  - "make all"
